### ISSUE TITLE
Review Request

### ISSUE THREAD

**Issue by rmccue** [WP-API/broker-client#1]
@joehoyle can you give spec.md a look and see if I'm making sense?

**Comment by joehoyle** [comment]
Cool, looking good - coupe thoughts:

I don't see why NDJSON is that necessary, informing the Client that an request has been issued seems unimportant, why not just keep the client waiting for a "normal" json response? Trying to do streaming is sucky with things like reverse proxies, I think it would be simpler to have say a 5 second timeout from Broker -> Server, so essentially the client can then assume a timeout of 10 seconds max, or something like that. Introducing the NDJSON I think makes this more complicated. Initial status "processing" is virtually what the "pending" response from the Broker is already saying.

I feel like the terminology / explanation misses the distinction between (excuse _my_ terminology) the "Application Tokens" and the "User Tokens". As I see it, the Broker is basically facilitating the Server creating the Application Tokens and passing them back to the Client, once that's done, it's back to Oauth 1.0 as normal for the Client and Server, to establish User Tokens. If i've understood that correctly, I think the spec could use a little natural language to make that clearer.

**Comment by rmccue** [comment]
> I don't see why NDJSON is that necessary, informing the Client that an request has been issued seems unimportant, why not just keep the client waiting for a "normal" json response?

The main reason is to try and avoid the connection timing out completely from the client's end. We might even want periodic `{"status": "processing"}` messages to keep the connection alive.

> Trying to do streaming is sucky with things like reverse proxies, I think it would be simpler to have say a 5 second timeout from Broker -> Server, so essentially the client can then assume a timeout of 10 seconds max, or something like that.

You're right that it does suck with reverse proxies, but we're expecting a limited number of brokers, and more advanced setup is not going to be an issue. Thankfully we don't need to worry about intermediary proxies, as we require HTTPS.

This problem is v similar to Server-Sent Events, so solutions can be borrowed from there.

> I feel like the terminology / explanation misses the distinction between (excuse my terminology) the "Application Tokens" and the "User Tokens".

I'll try and clarify that.

**Comment by rmccue** [comment]
> This problem is v similar to Server-Sent Events, so solutions can be borrowed from there.

(I actually considered using SSE with `text/event-stream`, but that's more complex for the client to handle than just newline delimited JSON.)

**Comment by rmccue** [comment]
Ended up dropping NDJSON after writing the example client; we have enough control of the protocol to get around problems without it.
